function Blogs() {
    return (
        <div id='Blogs' className="section">
        <h2>Blegs</h2>
        <h2>Blegs</h2>
        <h2>Blegs</h2>
        <h2>Blegs</h2>
        <h2>Blegs</h2>
        <h2>Blegs</h2>
        <h2>Blegs</h2>
        <h2>Blegs</h2>
        <h2>Blegs</h2>
        <h2>Blegs</h2>
        <h2>Blegs</h2>
        <h2>Blegs</h2>
        <h2>Blegs</h2>
        <h2>Blegs</h2>
        <h2>Blegs</h2>
        <h2>Blegs</h2>
        <h2>Blegs</h2>
        <h2>Blegs</h2>
        <h2>Blegs</h2>
        <h2>Blegs</h2>
        <h2>Blegs</h2>
        <h2>Blegs</h2>
        <h2>Blegs</h2>
        <h2>Blegs</h2>
        <h2>Blegs</h2>
        <h2>Blegs</h2>
        <h2>Blegs</h2>
        <h2>Blegs</h2>
        <h2>Blegs</h2>
        <h2>Blegs</h2>
        <h2>Blegs</h2>
        <h2>Blegs</h2>
        <h2>Blegs</h2>
        <h2>Blegs</h2>
        <h2>Blegs</h2>
        <h2>Blegs</h2>
        <h2>Blegs</h2>
        <h2>Blegs</h2>
        <h2>Blegs</h2>
        <h2>Blegs</h2>
        <h2>Blegs</h2>
        <h2>Blegs</h2>
        <h2>Blegs</h2>
        <h2>Blegs</h2>
        <h2>Blegs</h2>
        <h2>Blegs</h2>
        <h2>Blegs</h2>
        <h2>Blegs</h2>
        <h2>Blegs</h2>
        <h2>Blegs</h2>
    </div>
    )
}
export default Blogs